baseURL = "https://blog.zzsqwq.cn"
title = "Zs's Blog"
theme = "hugo-coder"
languageCode = "en"
publishDir= "public"
defaultContentLanguage = "en"
paginate = 20
# pygmentsStyle = "autumn"
# pygmentsCodeFences = true
# pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
googleAnalytics = 'G-WF7TH97J9X'

[markup.goldmark.renderer]
unsafe = true

[params]
  author = "zzsqwq"

  description = "Zs's personal website."

  keywords = "blog,developer,personal"

  info = ["An undergraduate student in NWPU", "Interested in Robotics and CV"]

  avatarURL = "images/avatar.png"

  favicon_32 = "images/favicon-32x32.png"

  dateFormat = "January 2, 2006"

  since = 2019

  math = true

  rtl = false

  colorScheme = "auto"

  hideColorSchemeToggle = false

  maxSeeAlsoItems = 5

  customCSS = []

  customSCSS = []

  customJS = []

[params.utterances]
  # repo = "zzsqwq/hugo-blog-comment" # https://utteranc.es/#heading-repository
  # issueTerm = "pathname" # https://utteranc.es/#heading-mapping
  # label = "comment" # https://utteranc.es/#heading-issue-label
  # theme = "preferred-color-scheme" # https://utteranc.es/#heading-theme

[params.giscus]
  repo = "zzsqwq/hugo-blog-comment"
  repoId = "R_kgDOGgU1qQ"
  category = "Announcements"
  categoryId  = "DIC_kwDOGgU1qc4CSX1m"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "dark"
  lang = "en"
  crossorigin = "anonymous"



[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/zzsqwq/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-2x fa-gitlab"
weight = 3
url = "https://gitlab.com/zzsqwq/"

[[params.social]]
name = "Telegram"
icon = "fa fa-2x fa-telegram"
weight = 2
url = "https://t.me/zzsqwq"

[[params.social]]
name = "LastBlog"
icon = "fa fa-2x fa-home"
weight = 6
url = "https://zzsqwq.cn/"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 4
url = "https://blog.zzsqwq.cn/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Posts"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Homepage"
weight = 5
url = "https://zzsqwq.cn/"

[[languages.en.menu.main]]
name = "Contact Me"
weight = 4
url = "contact/"

[[languages.en.menu.main]]
name = "Friends"
weight = 3
url = "friends/"
