baseURL = "https://www.zzsqwq.cn"
title = "Zs's Blog"
theme = "hugo-coder"
languageCode = "en"
publishDir= "public"
defaultContentLanguage = "en"
paginate = 20
# pygmentsStyle = "autumn"
# pygmentsCodeFences = true
# pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
googleAnalytics = 'G-Z6EM6V1PVC'


[params]
  author = "zzsqwq"

  description = "Zs's personal website."

  keywords = "blog,developer,personal"

  info = ["An undergraduate student in NWPU."]

  avatarURL = "images/avatar.png"

  favicon_32 = "images/favicon-32x32.png"

  dateFormat = "January 2, 2006"

  since = 2019

  math = true


  rtl = false

  colorScheme = "auto"

  hideColorSchemeToggle = false

  maxSeeAlsoItems = 5

  customCSS = []

  customSCSS = []

  customJS = []

[params.utterances]
  repo = "zzsqwq/hugo-blog-comment" # https://utteranc.es/#heading-repository
  issueTerm = "pathname" # https://utteranc.es/#heading-mapping
  label = "comment" # https://utteranc.es/#heading-issue-label
  theme = "github-light" # https://utteranc.es/#heading-theme


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/zzsqwq/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-2x fa-gitlab"
weight = 3
url = "https://gitlab.com/zzsqwq/"

[[params.social]]
name = "Telegram"
icon = "fa fa-2x fa-telegram"
weight = 2
url = "https://t.me/zzsqwq"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 6
url = "https://www.zzsqwq.cn/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact Me"
weight = 6
url = "contact/"

[[languages.en.menu.main]]
name = "Friends"
weight = 5
url = "friends/"